name: seller
description: GoSale Seller Application.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  dio: ^4.0.6
  lottie: ^1.3.0
  provider: ^6.0.2
  equatable: ^2.0.3
  connectivity_plus: ^2.3.0
  shared_preferences: ^2.0.15

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0

  firebase_core: ^1.16.0
  firebase_analytics: ^9.1.7
  firebase_crashlytics: ^2.7.2
  firebase_remote_config: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    # Add assets from the animations
    - assets/animations/
