name: seller
description: GoSale Seller Application.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  dio: ^4.0.6
  provider: ^6.0.2
  equatable: ^2.0.3
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
